---
# tasks file for iteasy.ansible.roles.change_ssh_port
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"
