- name: 기존 설정파일 백업 만들기
  ansible.builtin.copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.{{ backup_date }}.bak
    backup: true
    mode: '0644'

- name: 포트 변경하기
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: 'Port {{ new_port }}'
    state: present
  notify: Restart sshd

- name: SSH 설정파일 테스트
  ansible.builtin.command: sshd -t
  register: sshd_check
  failed_when: sshd_check.rc != 0

- name: 방화벽 세팅 (ufw)
  community.general.ufw:
    rule: allow
    port: "{{ new_port }}"
  notify: Update Firewall
