---
# handlers file for iteasy.ansible.roles.change_ssh_port
- name: Update Firewall
  ansible.builtin.debug:
    msg: |
      방화벽 포트 허용: "{{ new_port }}"

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true
